spring.profiles.active: dev

--- #------------------------- dev ----------------------------
#debug: true



--- #------------------------- production ----------------------------
#logging.path: /var/log
#logging.level.root: INFO

--- #------------------------- program ----------------------------
monitor:
  homeMessage: |
    GenSoft Saasapi has started successfully!
    The evn is [${spring.profiles.active}]

server:
  port: 8091
  address: localhost #192.168.1.105
  contextPath: /

management:
  port: 8081
  address: localhost
#  security:
#    enabled: false

spring:
  datasource:
    url: jdbc:mysql://192.168.1.105:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #max-wait: 10000
    #max-active: 50
  jpa:
    database: MYSQL
    hibernate:
      #ddl-auto: update
      naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"



#endpoints.health.sensitive: false

#spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"
