spring.profiles.active: dev

--- #------------------------- dev ----------------------------
#debug: true



--- #------------------------- production ----------------------------
#logging:
#  file: logs/saasapi.log
#  level: INFO

--- #------------------------- program ----------------------------

monitor:
  homeMessage: |
    GenSoft Saasapi has started successfully!
    The evn is [${spring.profiles.active}]

server:
  port: 8091
  address: localhost
  #address: 192.168.1.102
  contextPath: /

management:
  port: 8081
  address: localhost
#  security:
#    enabled: false

spring:
  datasource:
    url: jdbc:mysql://192.168.1.123:3306/gensoft?useLegacyDatetimeCode=false&serverTimezone=CST&useSSL=false&autoReconnect=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    #max-wait: 10000
    #max-active: 50
  jpa:
    database: MYSQL
    hibernate:
      #ddl-auto: update
      naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"

fileupload:
  path: /tmp/saasapi

websocket:
  port: 8999

#endpoints.health.sensitive: false

#spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"
