spring.profiles.active: dev

--- #------------------------- dev ----------------------------
debug: true

--- #------------------------- production ----------------------------
#logging.path: /var/log
#logging.level.root: INFO

--- #------------------------- program ----------------------------
monitor:
  homeMessage: |
    GenSoft Web has started successfully!
    The evn is [${spring.profiles.active}]

server:
  port: 8091
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    max-wait: 10000
    max-active: 50
  jpa:
    database: MYSQL
    #show-sql: true
    hibernate:
      #ddl-auto: update
      naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"

management:
  port: 8081
  address: localhost
#  security:
#    enabled: false


#endpoints.health.sensitive: false


#spring.jpa.properties.hibernate.dialect : "org.hibernate.dialect.MySQL5Dialect"
